### PR TITLE
DashPay libraries as the git submodules

### PR DESCRIPTION
**Pull request by tomasz-ludek**
In order to get it working all the local versions of libraries have to be removed (~.m2/repository/org/dashevo/*)

DashPay ready version of `dash-wallet` depends of three new libraries:

- https://github.com/dashevo/android-dpp
- https://github.com/dashevo/dapi-client-android
- https://github.com/dashevo/android-dashpay

(more details can be found in https://github.com/dashevo/dash-wallet/pull/380)

Apart from that libraries depend one of another:
- `dapi-client-android` depends on `android-dpp`
- `android-dashpay` depends on `android-dpp` and `dapi-client-android`

That is why, in order to become completely independent from published versions, those internal dependencies were replaced with direct references to submodules. That is why I created `develop` branches in each library repo and added the HEAD of those branches as a submodules to `dash-wallet` instead of referencing `master` branches, which should stay autonomic.

How to use it:
```
git clone https://github.com/dashevo/dash-wallet
git checkout evonet-develop-submodules
git submodule update --init --recursive
```

Info about submodules status:
```
git submodule status
```

Current status:
```
 efdfecce3f068d868edd2a02a0d34fb9af77f1e6 dapi-client (remotes/origin/develop)
 a9f37f2c82007d4f1489f9d6f4b7339f311888f2 dashpay (remotes/origin/develop)
 d2c6db11ff4ab31790c89967e6ad740fca692da3 dpp (remotes/origin/develop)
 5401869ae1a6f0235094fdfc93c51208c80d3000 wallet/cpp/dashj-bls/bls-signatures (0.1.15~38)
```

### CODE REVIEW

**Comment by HashEngineering** [comment]
@tomasz-ludek Can you explain the reasoning behind adding `develop` branch to each of the submodule repo's?

**Comment by HashEngineering** [comment]
Nevermind my last question.  I see the answer by looking at `dapi-client-android` and `android-dashpay` repos.

Is this submodule solution good as a permanent solution?

**Comment by tomasz-ludek** [comment]
No, it isn't ;)
I'm trying to get rid of them, but it isn't trivial since our libs aren't Android libs and I can't use build flavours...

**Comment by tomasz-ludek** [comment]
Not needed

**Pull request closed without merging**
