### PR TITLE
feat: Remove restore backup from external apps (NMA-885)

### PR DESCRIPTION
**Pull request by HashEngineering**
## Issue being fixed or feature implemented

Remove restore from backup file when activated from an external app.
Hide backup to file on security menu

## How Has This Been Tested?

- [ ] QA (Mobile Team)

## Checklist:

- [ ] I have performed a self-review of my own code and added comments where necessary
- [ ] I have added or updated relevant unit/integration/functional/e2e tests

### CODE REVIEW

**Review by tomasz-ludek — CHANGES_REQUESTED** [review]
Would be good to remove also the related string resources like restore_wallet_dialog_replace_warning, etc.

**Comment by HashEngineering** [comment]
All of the strings referenced by these deleted files are still in use in other parts of the app.

**Review by tomasz-ludek — APPROVED** [review]
Make sense, approved :)

**Comment by HashEngineering** [comment]
Travis fails because #665 is not merged.

**Pull request merged**
